name: Bug report
description: Report a bug with GDSodium
body:

- type: markdown
  attributes:
    value: |
      - Write a descriptive issue title above.
      - Search [open](https://github.com/stkptr/gdsodium/issues) and [closed](https://github.com/stkptr/gdsodium/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.
- type: input
  attributes:
    label: Godot version
    description: >
      Specify the Git commit hash of your Godot build.
    placeholder: v4.2.1.stable.official [b09f793f5]
  validations:
    required: true

- type: input
  attributes:
    label: GDSodium version
    description: >
      Specify the Git commit hash of the GDSodium submodule in your project. You can run `git status` inside the folder to check it.
  validations:
    required: true

- type: input
  attributes:
    label: System information
    description: |
      Specify the OS version.
    placeholder: Windows 10
  validations:
    required: true

- type: textarea
  attributes:
    label: Issue description
    description: |
      Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true